In [1]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings 

warnings.filterwarnings('ignore')

In [2]:
df=sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [5]:
df.drop(['alive','embark_town','adult_male','deck','who'],axis=1,inplace=True)

In [6]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,False
1,1,1,female,38.0,1,0,71.2833,C,First,False
2,1,3,female,26.0,0,0,7.9250,S,Third,True
3,1,1,female,35.0,1,0,53.1000,S,First,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True
...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,True
887,1,1,female,19.0,0,0,30.0000,S,First,True
888,0,3,female,NaN,1,2,23.4500,S,Third,False
889,1,1,male,26.0,0,0,30.0000,C,First,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,True

In [7]:
df['age'].fillna(df['age'].mean(),inplace=True)

In [8]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,False
1,1,1,female,38.0,1,0,71.2833,C,First,False
2,1,3,female,26.0,0,0,7.9250,S,Third,True
3,1,1,female,35.0,1,0,53.1000,S,First,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True

In [9]:
df.dropna(subset=['embarked'],inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   class     889 non-null    category
 9   alone     889 non-null    bool
dtypes: bool(1), category(1), float64(2), int64(4), object(2)
memory usage: 64.4+ KB

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [12]:
df['sex']= le.fit_transform(df['sex'])
df['embarked']= le.fit_transform(df['embarked'])  #S=2, C=0, Q=1
df['class']= le.fit_transform(df['class'])

In [13]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  class  alone
0         0       3    1  22.0      1      0   7.2500         2      2  False
1         1       1    0  38.0      1      0  71.2833         0      0  False
2         1       3    0  26.0      0      0   7.9250         2      2   True
3         1       1    0  35.0      1      0  53.1000         2      0  False
4         0       3    1  35.0      0      0   8.0500         2      2   True

In [14]:
df = df.astype(int)

In [15]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  class  alone
0         0       3    1   22      1      0     7         2      2      0
1         1       1    0   38      1      0    71         0      0      0
2         1       3    0   26      0      0     7         2      2      1
3         1       1    0   35      1      0    53         2      0      0
4         0       3    1   35      0      0     8         2      2      1

In [16]:
X = df.drop('survived',axis=1)
y = df['survived']

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [18]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [19]:
y_train

6      0
576    1
445    1
74     1
670    1
      ..
107    1
271    1
862    1
436    0
103    0
Name: survived, Length: 595, dtype: int64

In [20]:
y_pred = model.predict(X_test)

In [21]:
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0])

In [22]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
711    0
840    0
381    1
141    1
174    0
Name: survived, Length: 294, dtype: int64

In [23]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [24]:
accuracy_score(y_test,y_pred)

0.8163265306122449

In [25]:
confusion_matrix(y_test,y_pred)

array([[158,  26],
       [ 28,  82]])

In [26]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.86      0.85       184
           1       0.76      0.75      0.75       110

    accuracy                           0.82       294
   macro avg       0.80      0.80      0.80       294
weighted avg       0.82      0.82      0.82       294

KNN classification

In [27]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [28]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [29]:
from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [30]:
y_pred_knn = knn_model.predict(X_test_scaled)

In [31]:
accuracy_score(y_test,y_pred_knn)

0.7993197278911565

In [32]:
confusion_matrix(y_test,y_pred_knn)

array([[157,  27],
       [ 32,  78]])

In [33]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84       184
           1       0.74      0.71      0.73       110

    accuracy                           0.80       294
   macro avg       0.79      0.78      0.78       294
weighted avg       0.80      0.80      0.80       294

Naive bayes

In [34]:
from sklearn.naive_bayes import GaussianNB

In [35]:
modelNB = GaussianNB()

In [36]:
modelNB.fit(X_train, y_train)

GaussianNB()

In [37]:
y_pred_NB = modelNB.predict(X_test)

In [38]:
y_pred_NB

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1])

In [39]:
y_test

281    0
435    1
39     1
418    0
585    1
      ..
711    0
840    0
381    1
141    1
174    0
Name: survived, Length: 294, dtype: int64

In [40]:
accuracy_score(y_test,y_pred_NB)

0.7687074829931972

In [41]:
confusion_matrix(y_test,y_pred_NB)

array([[140,  44],
       [ 24,  86]])

In [42]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.76      0.80       184
           1       0.66      0.78      0.72       110

    accuracy                           0.77       294
   macro avg       0.76      0.77      0.76       294
weighted avg       0.78      0.77      0.77       294

DECISION TREE

In [43]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [44]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [45]:
model = DecisionTreeClassifier()
model.fit(X_train_scaled, y_train)

DecisionTreeClassifier()

In [46]:
y_pred_DT = model.predict(X_test_scaled)

In [47]:
accuracy_score(y_test, y_pred_DT)

0.7891156462585034

SVM

In [48]:
from sklearn.svm import SVC
model_svm = SVC(kernel= 'rbf')

In [49]:
model_svm.fit(X_train_scaled, y_train)

SVC()

In [50]:
y_pred_svm = model_svm.predict(X_test_scaled)

In [51]:
accuracy_score(y_test, y_pred_svm)

0.8163265306122449

In [52]:
confusion_matrix(y_test,y_pred_svm)

array([[159,  25],
       [ 29,  81]])

In [53]:
print(classification_report(y_test,y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.76      0.80       184
           1       0.66      0.78      0.72       110

    accuracy                           0.77       294
   macro avg       0.76      0.77      0.76       294
weighted avg       0.78      0.77      0.77       294

In [55]:
df

     survived  pclass  sex  age  sibsp  parch  fare  embarked  class  alone
0           0       3    1   22      1      0     7         2      2      0
1           1       1    0   38      1      0    71         0      0      0
2           1       3    0   26      0      0     7         2      2      1
3           1       1    0   35      1      0    53         2      0      0
4           0       3    1   35      0      0     8         2      2      1
..        ...     ...  ...  ...    ...    ...   ...       ...    ...    ...
886         0       2    1   27      0      0    13         2      1      1
887         1       1    0   19      0      0    30         2      0      1
888         0       3    0   29      1      2    23         2      2      0
889         1       1    1   26      0      0    30         0      0      1
890         0       3    1   32      0      0     7         1      2      1

[889 rows x 10 columns]

In [57]:
X = df.drop('survived', axis =1)
y = df['survived']

model turing

In [58]:
from sklearn.model_selection import cross_val_score

In [61]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [63]:
scores = cross_val_score(model_svm,X_scaled,y, cv = 5, scoring='accuracy')

In [64]:
print(scores)

[0.8258427  0.82022472 0.82022472 0.80898876 0.86440678]

In [65]:
print(scores.mean())

0.8279375357074844